### ISSUE TITLE
suggestion: add keyword 'CryptoJS' into README

### ISSUE THREAD

**Issue by tomasen** [Luzifer/go-openssl#1]
I been researching hours about how to decrypt aes encrypted data using golang.

I have to dig up source code from CryptoJS to find keyword 'openSSLEvpBytesToKey'. and found your project just for that.

Therefore I think add keyword 'CryptoJS' into README might help other people just like me

**Comment by Luzifer** [comment]
Thanks for your input! I've added a bit of text to the README so Google should find this library for future searches for CryptoJS and Go.
