### ISSUE TITLE
Update go.mod to v3

### ISSUE THREAD

**Issue by joy4eg** [Luzifer/go-openssl#12]
Hey,

Thanks for great library!
Could you update [go.mod](https://github.com/Luzifer/go-openssl/blob/master/go.mod) to the latest available release (v3) ?

Thanks :)

**Comment by Luzifer** [comment]
Thanks for reminding me! It's fixed now in `v3.0.1`. :see_no_evil:

**Comment by joy4eg** [comment]
Looks like smth went wrong:
```
$ go get -v gopkg.in/Luzifer/go-openssl.v3
Fetching https://gopkg.in/Luzifer/go-openssl.v3?go-get=1
Parsing meta tags from https://gopkg.in/Luzifer/go-openssl.v3?go-get=1 (status code 200)
get "gopkg.in/Luzifer/go-openssl.v3": found meta tag get.metaImport{Prefix:"gopkg.in/Luzifer/go-openssl.v3", VCS:"git", RepoRoot:"https://gopkg.in/Luzifer/go-openssl.v3"} at https://gopkg.in/Luzifer/go-openssl.v3?go-get=1
go: gopkg.in/Luzifer/go-openssl.v3@v3.0.1: go.mod has non-....v3 module path "github.com/Luzifer/go-openssl/v3" at revision v3.0.1
go: error loading module requirements
```

**Comment by Luzifer** [comment]
I'm not sure gopkg.in properly works with go modules.

Maybe try importing through `github.com/Luzifer/go-openssl/v3` or `github.com/Luzifer/go-openssl`...

**Comment by joy4eg** [comment]
`github.com/Luzifer/go-openssl/v3` works well.

Thank you!
