### ISSUE TITLE
Add possibility of using non base64 encoded data

### ISSUE THREAD

**Issue by mcgillowen** [Luzifer/go-openssl#14]
The openssl command line tool allows to choose if the encoded data should be base64 encoded or if the data to decrypt is in base64 encoding.

I believe we should have an option to use this library without having to encode or decode the data with base64 encoding.

If nobody has any objections I would like to work on this and then submit a PR.

**Comment by Luzifer** [comment]
I like the suggestion! When adding this please add tests against the OpenSSL CLI and if possible ensure backwards-compatibility in order not to break implementations based on this library.
