### ISSUE TITLE
How to decrypt file?

### ISSUE THREAD

**Issue by ly020044** [Luzifer/go-openssl#19]
Hi ,

I want to use openssl command decrypt file, But an error occurred (bad magic number).
encrypt file code:
`data, err := ioutil.ReadFile("../TODO.md")
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	key, _ := ioutil.ReadFile("key.pem")

	enc, err := openssl.New().EncryptBytes(string(key), data, openssl.PBKDF2SHA256)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	ioutil.WriteFile("enc.md", enc, 0644)`
decrypt command:
`openssl enc -d -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -pass pass:p9s7SEugpIz+SQBT9WwKKvTfphhmwGsH2d2mlZHEd58=`

**Comment by Luzifer** [comment]
```go
package main

import (
        "fmt"
        "io/ioutil"

        openssl "github.com/Luzifer/go-openssl/v4"
)

func main() {
        data, err := ioutil.ReadFile("TODO.md")
        if err != nil {
                fmt.Println(err.Error())
                return
        }

        enc, err := openssl.New().EncryptBytes("p9s7SEugpIz+SQBT9WwKKvTfphhmwGsH2d2mlZHEd58=", data, openssl.PBKDF2SHA256)
        if err != nil {
                fmt.Println(err.Error())
                return
        }

        ioutil.WriteFile("enc.md", append(enc, '\n'), 0o644)
}
```

```console
# go run .
# openssl enc -d -base64 -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -pass pass:p9s7SEugpIz+SQBT9WwKKvTfphhmwGsH2d2mlZHEd58=
# md5sum TODO.md dec.md 
d8e8fca2dc0f896fd7cb4cb0031ba249  TODO.md
d8e8fca2dc0f896fd7cb4cb0031ba249  dec.md
```

What has changed in comparison to your code:
- Replaced the read of `key.pem` with the password used in the command (is that the content of the `key.pem`?)
- Added a newline to EOF of the written file (OpenSSL needs a trailing newline when reading base64 input)
- Added `-base64` parameter to the openssl command as the library uses base64 wrapped data

**Comment by ly020044** [comment]
Yeah,  This is content with key.pem file.
It worked nice!!!!!

`openssl enc -d -base64 -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -kfile key.pem`

Thanks so much!

**Comment by iredmail** [comment]
I can not get it working with exactly same Go code, running openssl to decrypt file always get `error reading input file` on macOS with libressl (version 2.8.3), and `bad magic number` on Ubuntu 20.04 with openssl (version 1.1.1f).

I'm sure it had below line to append a newline after base64:
```
        ioutil.WriteFile("enc.md", append(enc, '\n'), 0o644)
```

Decrypt with command:
```
openssl enc -d -base64 -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -pass pass:YOURPASSWORD
```

**Comment by Luzifer** [comment]
Hm works fine with `openssl 1.1.1f` for me in an `ubuntu:20.04` container…

`bad magic number` indicates you forgot the `-base64` parameter…

**Comment by iredmail** [comment]
Dear @Luzifer,

Did you ever test with libressl?
I tested on macOS with libressl 2.8.3, seems it's not compatible and cannot decrypt no matter what arguments i used for `openssl enc -d`.

**Comment by Luzifer** [comment]
I just did with `libressl 3.2.2`:

```console
[root@09038c305794 ossltest]# libressl-openssl version
LibreSSL 3.2.2
[root@09038c305794 ossltest]# rm dec.md 
[root@09038c305794 ossltest]# libressl-openssl enc -d -base64 -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -pass pass:p9s7SEugpIz+SQBT9WwKKvTfphhmwGsH2d2mlZHEd58=
[root@09038c305794 ossltest]# md5sum TODO.md dec.md 
d8e8fca2dc0f896fd7cb4cb0031ba249  TODO.md
d8e8fca2dc0f896fd7cb4cb0031ba249  dec.md
```

> LibreSSL 2.9.0, 2.8.3, 2.7.5 (December 15th, 2018)
> https://www.libressl.org/releases.html

It looks like you do have quite an old version of libressl and it looks like PBKDF2 support was added in `libressl 2.9.1`:
https://github.com/libressl-portable/portable/blob/c50f8e2c6c066be053a2886cfddc41992fb2ca82/ChangeLog#L560

So in order to decrypt a file encrypted using go-openssl you probably (I don't have libressl 2.8.3 available to test) need to use `openssl.BytesToKeySHA256` instead of `openssl.PBKDF2SHA256`. Also you might need the parameter `-md sha256` specified in the command as old OpenSSL versions (and therefore maybe also libressl) used `-md md5` as default…

**Comment by iredmail** [comment]
> ```
> [root@09038c305794 ossltest]# libressl-openssl enc -d -base64 -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -pass pass:p9s7SEugpIz+SQBT9WwKKvTfphhmwGsH2d2mlZHEd58=
> ```

I installed LibreSSL 3.2.3 with Homebrew, and the tests are very interesting on macOS.
Your command doesn't work with 3.2.3, but works without `-base64` argument:

```
openssl enc -d -aes-256-cbc -pbkdf2 -in enc.md -out dec.md -pass pass:p9s7SEugpIz+SQBT9WwKKvTfphhmwGsH2d2mlZHEd58=
```

Another problem is not related to `go-openssl`, but very weird on macOS.
I try to verify the decrypted file content with `exec.Command(...)` function, it always failed with error `bad decrypt`.

```
	args := []string{
		"enc",
		"-d",
		"-aes-256-cbc",
		"-pbkdf2",
		"-in",
		fname,
		"-out",
		outputFileName,
		"-pass",
		fmt.Sprintf("pass:'%s'", pass),
	}

	// `/usr/local/opt/libressl/bin/openssl` is LibreSSL 3.2.3.
	cmd := exec.Command("/usr/local/opt/libressl/bin/openssl", args...)
	cmd.Stderr = os.Stdout

	out, err := cmd.Output()
	fmt.Printf("Err: %v\n", err)  // prints `bad decrypt`.
```

**Comment by iredmail** [comment]
I got it fixed by removing single quotes after `pass:`.
Thank you very much, @Luzifer :)
