### ISSUE TITLE
BytesToKeyMD5 and PBKDF2SHA256

### ISSUE THREAD

**Issue by buzzy** [Luzifer/go-openssl#23]
In the encrypt/decrypt example, the third parameter is BytesToKeyMD5 and PBKDF2SHA256.
Where are these coming from? It's not clear where they are defined and the example do not compile without errors the way they stand now.

./main.go:286:62: undefined: BytesToKeyMD5

It seems to compile cleanly if it's replaced with openssl.BytesToKeyMD5 though.

**Comment by Luzifer** [comment]
> It seems to compile cleanly if it's replaced with `openssl.BytesToKeyMD5` though.

You answered your question. As the example is within the `openssl` package it does not reference the package. If you use it outside of the package you need to reference those functions by specifying the package.
