### ISSUE TITLE
invalid padding

### ISSUE THREAD

**Issue by alidehghan** [Luzifer/go-openssl#31]
I use openSSL 3 with following command to encrypt the file:

openssl aes-256-cbc -in input.zip -out input.zip.enc -pass pass:111111111 -md md5 -pbkdf2

and use the library  as follow

`	o := openssl.New()

	encBytes, err := os.ReadFile(srcFile)
	if err != nil {
		fmt.Printf("err in reading encrypted file, err:%s\n", err)
		return err
	}

	cg := openssl.NewBytesToKeyGenerator(func() hash.Hash { return md5.New() })
	dec, err := o.DecryptBinaryBytes(password, encBytes, cg)
	if err != nil {
		fmt.Printf("err in decryption occurred: %s\n", err)
		return err
	}

	if err := os.WriteFile(destFile, dec, 0777); err != nil {
		fmt.Printf("err in writing decrypted file, err:%s", err.Error())
		return err
	}
`

and in line **dec, err := o.DecryptBinaryBytes(password, encBytes, cg)** error occurs :invalid padding

I will be appreciate if you help me on that

**Comment by Luzifer** [comment]
You are using `-pbkdf2` in your command. Use `openssl.PBKDF2MD5` as credential generator. The generator you're using is for the old non-PBKDF2 key derivation function (available as `openssl.BytesToKeyMD5`).

See included generators: https://pkg.go.dev/github.com/Luzifer/go-openssl/v4#pkg-variables

**Comment by alidehghan** [comment]
Yes, you are right, thanks for your help.
