### ISSUE TITLE
Decrypting encodings with openssl --nosalt

### ISSUE THREAD

**Issue by hrmrules** [Luzifer/go-openssl#32]
Is it possible to use this library to decode encrypted text that was encrypted with the openssl --nosalt parameter?

Openssl text encoded with normal salt works perfectly, but unsalted ciphertext results in "does not appear to have been encrypted with OpenSSL, salt header missing".

**Comment by Luzifer** [comment]
Why would you not salt the key derivation?

No, this is not supported.

**Comment by hrmrules** [comment]
Thanks. Individual values in files are encrypted - we cannot use salt because re-encryption should give identical results. For versioning purposes. Otherwise each individual change would make everything change.

**Comment by Luzifer** [comment]
You could use a static salt (even though the library discourages the use of a static salt for security reasons it is possible)… That would yield the same result on each encrypt…

**Comment by hrmrules** [comment]
I already do. The question was about having to re-encrypt everything with your go library without having unchanged plaintexts changing to another encoded value.
They were originally encoded with openssl --nosalt.

But we have decided to accept the minor inconvenience of having everything change this one time as we migrate to a new tool based on your go library (decrypting with openssl and encrypting with your library).

Your library works very well - thank you very much for it.
