### ISSUE TITLE
Compatibility issues with OpenSSL 1.1.0g

### ISSUE THREAD

**Issue by steffenfritz** [Luzifer/go-openssl#5]
Hi!

I created a cipher text with

    echo "test"|openssl enc -aes-256-cbc -a

If I try to decrypt with the following code I get "An error occurred: invalid padding" 

    package main

    import (
            "fmt"
            "github.com/Luzifer/go-openssl"
    )

    func main() {
            // ciphertext created with echo "test" | openssl enc -aes-256-cbc -a
            ciphertext := "U2FsdGVkX18Tx7rNQv4muFANdygev6quM5N1xa1+6Nw="
            pass := "aaaabbbbccccdddd"

            o := openssl.New()

            dec, err := o.DecryptString(pass, ciphertext)
            if err != nil {
                    fmt.Printf("An error occurred: %s\n", err)
            }

            fmt.Printf("Decrypted text: %s\n", string(dec))

    }

Used openssl version: OpenSSL 1.1.0g  2 Nov 2017

**Comment by Luzifer** [comment]
With OpenSSL version 1.1.0 the default hashing function for `openssl enc` changed. Before it was a MD5 hash, now it is an SHA1 hash. Currently you need to specify the hash function when using OpenSSL >= 1.1.0:

```go
package main

import (
        "fmt"

        "github.com/Luzifer/go-openssl"
)

func ExampleOpenSSLVersions() {
        // [root@arch /]# openssl version
        // OpenSSL 1.1.0g  2 Nov 2017
        //
        // [root@arch /]# echo "test" | openssl enc -aes-256-cbc -a -k aaaabbbbccccdddd -md md5
        // U2FsdGVkX1+8QZjV1dy24/DJsW4+OTAjO9bKPD7SDwI=
        executeTest("Arch (1.1.0g) MD5", "U2FsdGVkX1/C0zsZbWg5HLSl+d1OpA2N71RrZL0okr0=")
        //
        // [root@arch /]# echo "test" | openssl enc -aes-256-cbc -a -k aaaabbbbccccdddd
        // U2FsdGVkX1/th7kZ2pdVr1NXMefaNrONYF63TGUItic=
        executeTest("Arch (1.1.0g) Default", "U2FsdGVkX18Cl2VRzmUaYPw3vJkIfBVjMhrUjGTCpKI=")
        //
        // [root@alpine /]# openssl version
        // OpenSSL 1.0.2n  7 Dec 2017
        //
        // [root@alpine /]# echo "test" | openssl enc -aes-256-cbc -a -k aaaabbbbccccdddd
        // U2FsdGVkX1/HAXt3UrPNPlzn6de6Y7PM4WZehKI5th0=
        executeTest("Alpine (1.0.2n) Default", "U2FsdGVkX1+65xZJLEyeTzHrr5RmCEetN+Bnq8AKyao=")
        //
        // [root@alpine /]# echo "test" | openssl enc -aes-256-cbc -a -k aaaabbbbccccdddd -md sha1
        // U2FsdGVkX1/HAXt3UrPNPlzn6de6Y7PM4WZehKI5th0=
        executeTest("Alpine (1.0.2n) SHA1", "U2FsdGVkX1/oH4paueBC/dAB/GBEJhhaE/EWC7vLoyM=")

        // Output: Success decrypt from "Arch (1.1.0g) MD5": test
        // Failed decrypt from "Arch (1.1.0g) Default": invalid padding
        // Success decrypt from "Alpine (1.0.2n) Default": test
        // Failed decrypt from "Alpine (1.0.2n) SHA1": invalid padding
}

func executeTest(desc, ciphertext string) {
        pass := "aaaabbbbccccdddd"

        o := openssl.New()

        dec, err := o.DecryptString(pass, ciphertext)
        if err != nil {
                fmt.Printf("Failed decrypt from %q: %s\n", desc, err)
                return
        }

        fmt.Printf("Success decrypt from %q: %s", desc, string(dec))
}
```

```console
$ go test -v
=== RUN   ExampleOpenSSLVersions
--- PASS: ExampleOpenSSLVersions (0.00s)
PASS
ok      test    0.002s
```

Though the experience is not consistent: When using password `foobar` with the same commands shown above you will be able to decrypt the string but will receive garbled text.

In the end I need to figure out how to detect the hashing function without knowledge about the content of the message and adjust the decryption… Until now I have no clue how to detect the hashing function. When the decryption is failing one could also try the SHA1 hashing function but if it succeeds with garbled text this is not possible…

----

**Edit:** I was wrong about the hashing algorithm as `sha256` is used, not `sha1` as described above. The result though is the same…

**Comment by steffenfritz** [comment]
Thanks for your explanation!

**Comment by Luzifer** [comment]
Added a hint for this in the README and will keep this issue open for further research and implementation of additional hashing algorithms.

**Comment by Luzifer** [comment]
Good news: Thanks to @yoozoo there is now support for OpenSSL <1.1.0c **and** >1.1.0c!
