### ISSUE TITLE
How to EncryptFile?

### ISSUE THREAD

**Issue by mhlee0328** [Luzifer/go-openssl#6]
Hi ,
I tried `o.EncryptString(passphrase, plaintext)`, it worked nice ! ^^ 
How to encrypt a file MyFile.tar.gz  into MyFile.enc ?

I use command line in OpenSSL 1.1.0f as below,
```console
$ openssl aes-256-cbc -in MyFile.tar.gz -out MyFile.enc -pass pass:MyPassWord1234
```

**Comment by Luzifer** [comment]
Hey,

At first you need to add some more flags to your encoding to be compatible:
- `-a` to encode the result using base64
- `-md md5` to use MD5 key derivation (see hint in README.md)

Afterwards you could do something like this:

```go
content, _ := ioutil.ReadFile("MyFile.tar.gz")
enc, _ := openssl.New().EncryptBytes("MyPassWord1234", content)
ioutil.WriteFile("MyFile.enc", enc, 0644)
```

And for decryption:

```go
content, _ := ioutil.ReadFile("MyFile.enc")
dec, _ := openssl.New().DecryptBytes("MyPassWord1234", content)
ioutil.WriteFile("MyFile.tar.gz", dec, 0644)
```

(Yep, `EncryptBytes` is a new function added in `v1.2.0` which spares you from converting the read bytes into a string...)

**Comment by mhlee0328** [comment]
Hi Luzifer,

Thank you for the update and great package !
It worked now with new func EncryptBytes( ) and DecryptBytes( ) !

If I do go-openssl::EncryptBytes (MyFile.enc ) , this file can't decrypted in OpenSSL by using the same 
 "MyPassWord1234".
Also the encrypted file from OpenSSL ,it can't decrypted by go-openssl .
They all return the error message "bad magic number".
Is that Salt or different between OpenSSL and go-openssl ? 

Anyway,
My purpose is do not want to using system call EXEC ( /bin/sh openssl ... ) in the golang ,
The reason is that causes the risk of /proc/pid/cmdline leaking sensitive parameters , 
If I wrap the password or keyfile directly in the golang project ( by using go-openssl package ) 
Would it become more security then using system Call  Exec(OpenSSL ...) ?

**Comment by Luzifer** [comment]
Lets see:

```go
package main

import (
        "io/ioutil"

        openssl "github.com/Luzifer/go-openssl"
)

func main() {
        content, _ := ioutil.ReadFile("myfile.txt")
        enc, _ := openssl.New().EncryptBytes("MyPassWord1234", content)
        enc = append(enc, '\n')
        ioutil.WriteFile("MyFile.enc", enc, 0644)
}
```

```console
$ cat myfile.txt
hi

$ go run *.go

$ openssl enc -d -aes-256-cbc -pass pass:MyPassWord1234 -base64 -md md5 -in MyFile.enc
hi
```

The only thing I've added is the newline to be appended: OpenSSL for some reason requires a file to end with a newline while a string does not need to be newline terminated.

The error `bad magic number` appears when not specifying the file is base64 encoded (see the missing `-base64 / -a`):

```console
$ openssl enc -d -aes-256-cbc -pass pass:MyPassWord1234 -md md5 -in MyFile.enc
bad magic number
```

**Edit:** Though I'm using `openssl enc` you also can use `openssl aes-256-cbc`:

```console
$ openssl aes-256-cbc -d -pass pass:MyPassWord1234 -base64 -md md5 -in MyFile.enc
hi
```
