### ISSUE TITLE
License

### ISSUE THREAD

**Issue by VojtechBartos** [Luzifer/go-openssl#7]
Hey there,

just quick question, what's the license of the library? Couldn't find it. MIT ?

Thanks, 
Vojta

**Comment by Luzifer** [comment]
Good point… It should have Apache 2.0 license, will it add soon…

Thanks for the hint! 🙂

**Comment by VojtechBartos** [comment]
Great, let me know when it's added ;)

Thanks!

**Comment by Luzifer** [comment]
Done 🙂

**Comment by VojtechBartos** [comment]
Haha, you are super fast, thanks!
